---
myConfig:
    PDCARedirectURL_DEV: http://localhost:40000/#/threeThAuth
    PDCARedirectURL_PRO: http://grails.online/#/threeThAuth
    PDCASERVERRedirectURL_DEV: http://dev.pdca.vip/api/authLogin/authLoginSuccess
    PDCASERVERRedirectURL_PRO: http://grails.online/api/authLogin/authLoginSuccess
beans:
    securityInterceptor:
        order: 20
    corsInterceptor:
        order: 10
server:
    port: 8001
grails:
    cors:
        enabled: true
        allowedOrigins:
            - http://localhost:40000
            - http://pdca.vip:8002
            - http://dev.pdca.vip:40000
            - http://grails.online
    profile: web
    codegen:
        defaultPackage: pdca.server
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
#    pooled: true
#    jmxExport: true
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    dbCreate: create-drop
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#   ===========
    pooled : true
    driverClassName : "com.mysql.cj.jdbc.Driver"
    dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    username : "root"
    password : "11111111"
    type : "com.zaxxer.hikari.HikariDataSource"
    logSql : false
    properties :
        jmxEnabled : true
        initialSize : 5
        maxActive : 50
        minIdle : 5
        maxIdle : 25
        maxWait : 10000
        maxAge : 10 * 60000
        timeBetweenEvictionRunsMillis : 5000
        minEvictableIdleTimeMillis : 60000
        validationQuery : "SELECT 1"
        validationQueryTimeout : 3
        validationInterval : 15000
        testOnBorrow : true
        testWhileIdle : true
        testOnReturn : false
        jdbcInterceptors : "ConnectionState;StatementCache(max=200)"
        defaultTransactionIsolation : java.sql.Connection.TRANSACTION_READ_COMMITTED


environments:
    development:
        dataSource:
            dbCreate: "update"
            url: "jdbc:mysql://localhost:3306/pdca?useUnicode=true&characterEncoding=utf-8&useSSL=false"
#    test:
#        dataSource:
#            dbCreate: update
#            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            username: "pdca_mysql"
            password: "Wufei7260189"
            dbCreate: "update"
            url: "jdbc:mysql://rm-uf6n4t6j1gdj7c9f5125010.mysql.rds.aliyuncs.com:3306/pdca?useUnicode=true&characterEncoding=utf-8&useSSL=false"

